# Generated by Django 4.2.7 on 2026-01-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_admin_panel',
            field=models.BooleanField(default=False, verbose_name='Доступ к админ-панели'),
        ),
    ]
