# Generated by Django 4.2.7 on 2026-01-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_access_admin_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_access_admin_panel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token_created',
        ),
    ]
