# Generated by Django 4.2.7 on 2026-01-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_can_access_admin_panel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_admin_panel',
            field=models.BooleanField(default=False, verbose_name='Доступ к админ-панели'),
        ),
    ]
