# Generated by Django 4.2.7 on 2026-01-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_can_access_admin_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Токен сброса пароля'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания токена сброса пароля'),
        ),
    ]
