# Generated by Django 4.2.7 on 2026-01-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "__first__"),
        ("accounts", "0006_user_password_reset_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="schedule.group",
                verbose_name="Группа",
            ),
        ),
    ]
