# Generated by Django 4.2.7 on 2025-12-18 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.JSONField(verbose_name='Значение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем')),
            ],
            options={
                'verbose_name': 'Системная настройка',
                'verbose_name_plural': 'Системные настройки',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('action', models.CharField(choices=[('approve', 'Одобрено'), ('reject', 'Отклонено'), ('delete', 'Удалено'), ('edit', 'Отредактировано')], max_length=20, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Новый статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата действия')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Лог модерации',
                'verbose_name_plural': 'Логи модерации',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['moderator', '-created_at'], name='moderation__moderat_68c327_idx'), models.Index(fields=['content_type', 'object_id'], name='moderation__content_a6fbd8_idx'), models.Index(fields=['action', '-created_at'], name='moderation__action_160273_idx')],
            },
        ),
    ]
