# Generated by Django 4.2.7 on 2026-01-07 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=300, unique=True, verbose_name="Название института"
                    ),
                ),
                (
                    "sstu_id",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="ID в системе СГТУ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Институт",
                "verbose_name_plural": "Институты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Начало обновления"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание обновления"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Успешно"),
                            ("failed", "Ошибка"),
                            ("in_progress", "В процессе"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "groups_updated",
                    models.IntegerField(default=0, verbose_name="Обновлено групп"),
                ),
                (
                    "lessons_added",
                    models.IntegerField(default=0, verbose_name="Добавлено занятий"),
                ),
                (
                    "lessons_removed",
                    models.IntegerField(default=0, verbose_name="Удалено занятий"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
            ],
            options={
                "verbose_name": "Обновление расписания",
                "verbose_name_plural": "Обновления расписания",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Название предмета"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="ФИО преподавателя"),
                ),
                (
                    "sstu_id",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="ID в системе СГТУ",
                    ),
                ),
                (
                    "sstu_profile_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на профиль СГТУ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["sstu_id"], name="schedule_te_sstu_id_020f1e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Название группы",
                    ),
                ),
                (
                    "sstu_id",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="ID в системе СГТУ",
                    ),
                ),
                (
                    "education_form",
                    models.CharField(
                        choices=[
                            ("full_time", "Очная"),
                            ("part_time", "Заочная"),
                            ("evening", "Очно-заочная"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="Форма обучения",
                    ),
                ),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("bachelor", "Бакалавриат"),
                            ("master", "Магистратура"),
                            ("specialty", "Специалитет"),
                            ("postgraduate", "Аспирантура"),
                        ],
                        default="bachelor",
                        max_length=20,
                        verbose_name="Тип обучения",
                    ),
                ),
                (
                    "course_number",
                    models.IntegerField(blank=True, null=True, verbose_name="Курс"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="schedule.institute",
                        verbose_name="Институт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("лек", "Лекция"),
                            ("пр", "Практика"),
                            ("лаб", "Лабораторная"),
                            ("экз", "Экзамен"),
                            ("конс", "Консультация"),
                            ("other", "Другое"),
                        ],
                        default="лек",
                        max_length=10,
                        verbose_name="Тип занятия",
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Аудитория"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "Понедельник"),
                            (2, "Вторник"),
                            (3, "Среда"),
                            (4, "Четверг"),
                            (5, "Пятница"),
                            (6, "Суббота"),
                            (7, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("lesson_number", models.IntegerField(verbose_name="Номер пары (1-6)")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "specific_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Конкретная дата (для экзаменов)",
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Номер недели"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="schedule.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="schedule.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="schedule.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Занятия",
                "ordering": ["weekday", "lesson_number", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["group", "weekday", "is_active"],
                        name="schedule_le_group_i_a75b28_idx",
                    ),
                    models.Index(
                        fields=["teacher", "weekday"],
                        name="schedule_le_teacher_66a0e0_idx",
                    ),
                    models.Index(
                        fields=["specific_date"], name="schedule_le_specifi_5e7252_idx"
                    ),
                    models.Index(
                        fields=["week_number", "weekday"],
                        name="schedule_le_week_nu_4e46e5_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["institute", "name"], name="schedule_gr_institu_fd518c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["sstu_id"], name="schedule_gr_sstu_id_8885be_idx"
            ),
        ),
    ]
