# Generated by Django 4.2.7 on 2025-12-18 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('institute', 'Институт'), ('direction', 'Направление'), ('subject', 'Предмет'), ('teacher', 'Преподаватель')], max_length=20, verbose_name='Тип ветки')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('moderation_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_branches', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='branches.branch', verbose_name='Родительская ветка')),
            ],
            options={
                'verbose_name': 'Ветка',
                'verbose_name_plural': 'Ветки',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BranchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название новой ветки')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('moderation_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_request', to='branches.branch', verbose_name='Созданная ветка')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_branch_requests', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_requests', to='branches.branch', verbose_name='Родительская ветка')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_requests', to=settings.AUTH_USER_MODEL, verbose_name='Запросивший')),
            ],
            options={
                'verbose_name': 'Запрос на ветку',
                'verbose_name_plural': 'Запросы на ветки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='branches_br_status_948c6a_idx'), models.Index(fields=['requester', 'status'], name='branches_br_request_6b8c05_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['parent', 'status'], name='branches_br_parent__4d917a_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['type', 'status'], name='branches_br_type_480ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['creator', 'status'], name='branches_br_creator_45f4be_idx'),
        ),
    ]
