# Generated by Django 4.2.7 on 2025-12-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='type',
            field=models.CharField(choices=[('institute', 'Институт'), ('direction', 'Направление'), ('subject', 'Предмет'), ('course', 'Курс'), ('teacher', 'Преподаватель')], max_length=20, verbose_name='Тип ветки'),
        ),
    ]
