# Generated by Django 4.2.7 on 2026-01-03 10:44

from django.db import migrations, models


def migrate_branch_types_forward(apps, schema_editor):
    """Migrate branch types: direction (as department) -> department, subject -> direction."""
    Branch = apps.get_model('branches', 'Branch')
    
    # Convert direction branches that are children of institute to department
    Branch.objects.filter(
        type='direction',
        parent__type='institute'
    ).update(type='department')
    
    # Convert subject branches to direction
    Branch.objects.filter(type='subject').update(type='direction')


def migrate_branch_types_backward(apps, schema_editor):
    """Reverse migration: department -> direction, direction (former subject) -> subject."""
    Branch = apps.get_model('branches', 'Branch')
    
    # Convert department branches back to direction
    Branch.objects.filter(type='department').update(type='direction')
    
    # Note: We can't perfectly reverse direction->subject conversion
    # as we don't know which directions were subjects
    # This is a limitation of the migration


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_type'),
    ]

    operations = [
        migrations.RunPython(migrate_branch_types_forward, migrate_branch_types_backward),
        migrations.AlterField(
            model_name='branch',
            name='type',
            field=models.CharField(choices=[('institute', 'Институт'), ('department', 'Кафедра'), ('direction', 'Направление'), ('course', 'Курс'), ('teacher', 'Преподаватель')], max_length=20, verbose_name='Тип ветки'),
        ),
    ]
