# Generated by Django 4.2.7 on 2026-01-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='type',
            field=models.CharField(choices=[('institute', 'Институт'), ('department', 'Кафедра'), ('direction', 'Направление'), ('course', 'Курс'), ('teacher', 'Преподаватель')], max_length=20, verbose_name='Тип ветки'),
        ),
    ]
