# Generated by Django 4.2.7 on 2026-01-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_alter_branch_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="type",
            field=models.CharField(
                choices=[
                    ("institute", "Институт"),
                    ("direction", "Направление"),
                    ("subject", "Предмет"),
                    ("teacher", "Преподаватель"),
                ],
                max_length=20,
                verbose_name="Тип ветки",
            ),
        ),
    ]
