# Generated by Django 4.2.7 on 2025-12-18 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('moderation_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Средняя оценка')),
                ('ratings_count', models.IntegerField(default=0, verbose_name='Количество оценок')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Количество скачиваний')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='branches.branch', verbose_name='Ветка')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_materials', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название тега')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('materials', models.ManyToManyField(blank=True, related_name='tags', to='materials.material', verbose_name='Материалы')),
            ],
            options={
                'verbose_name': 'Тег материала',
                'verbose_name_plural': 'Теги материалов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/%Y/%m/%d/', validators=[materials.models.validate_file_extension, materials.models.validate_file_size], verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байты)')),
                ('file_type', models.CharField(max_length=50, verbose_name='Тип файла')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к файлу')),
                ('upload_order', models.IntegerField(default=0, verbose_name='Порядок загрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='materials.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Файл материала',
                'verbose_name_plural': 'Файлы материалов',
                'ordering': ['upload_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='materials.material', verbose_name='Материал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка материала',
                'verbose_name_plural': 'Оценки материалов',
                'indexes': [models.Index(fields=['material', 'user'], name='materials_m_materia_272fe9_idx')],
                'unique_together': {('material', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MaterialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='materials.material', verbose_name='Материал')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='materials.materialcomment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий к материалу',
                'verbose_name_plural': 'Комментарии к материалам',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['material', 'created_at'], name='materials_m_materia_352665_idx'), models.Index(fields=['parent'], name='materials_m_parent__f1734b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['branch', 'status'], name='materials_m_branch__21be46_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['author', 'status'], name='materials_m_author__101b71_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['status', '-created_at'], name='materials_m_status_bac842_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-average_rating', '-ratings_count'], name='materials_m_average_2a8dca_idx'),
        ),
    ]
